[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"
authors = ["Joey Harrison"]
license = "MIT"

[dependencies]
image = "0.24.1"
derive_more = "0.99.17"
rayon = "1.5.1"
rand = "0.8.5"
indicatif = { version = "0.16", features = ["rayon"] }
